NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12

NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -25

NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0

NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 20
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0

NDefines.NMilitary.WARGOAL_MAX_BONUS = 35
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.7

NDefines.NReligion.MAX_CHURCH_POWER = 300